### PR TITLE
Add code of conduct

### LINKED ISSUE #3: Add Code of Conduct
Mellanie provided this from HNL JS for us to alter/use: [https://github.com/hnljs/about-us/blob/master/code-of-conduct.md](https://github.com/hnljs/about-us/blob/master/code-of-conduct.md)

### PR DESCRIPTION
**Pull request by axelson**
Compile the code of conduct into the code at compile time so that we're not reading a markdown file and parsing it into html at run-time.

Fixes #3

### CODE REVIEW

**Comment by mudphone** [comment]
Cool idea. So, we get to keep the static content static? I'm guessing we can add css as normal, when the time comes?

**Comment by mudphone** [comment]
Doh, I hit the wrong button!

**Review by mudphone — COMMENTED** [review]
Apparently I was supposed to review this (by using the review feature). I took a look on my machine after downloading the branch. One question I have is the "Contact Info" form "Report Anonomously" (sp). Is that our form? or is that copied from elsewhere?

**Comment by mudphone** [comment]
I should have rebased this. Doh!

**Comment by axelson** [comment]
> So, we get to keep the static content static?

It is mostly static, it's still hitting a normal controller but at least we're not paying to hit the disk and convert it to html again.

> I'm guessing we can add css as normal, when the time comes?

Yeah that should be straightforward, we just need to drop the rendered html within a template.

> One question I have is the "Contact Info" form "Report Anonomously" (sp). Is that our form? or is that copied from elsewhere?

Yeah that is our form (just a simple copy from hnl.js's form). I've added you as a collaborator on the form.

**Pull request merged**
